name: Build

on:
  push:
    branches: 
      - main
      - release/**

  pull_request:
    branches: 
      - main

env:
  JAVA_DISTRIBUTION: 'microsoft'
  JAVA_VERSION: 17
  NET_VERSION: 9.0.301
  OUTPUT_DIR: ${{ github.workspace }}/output

jobs:
  build:
    runs-on: macos-15
    
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      with:
        fetch-depth: 0
        fetch-tags: true

    - name: Install .NET ${{ env.NET_VERSION }}
      uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9
      with:
        dotnet-version: ${{ env.NET_VERSION }}

    - name: Restore .NET tools
      run: dotnet tool restore

    - name: Install .NET workloads
      run: |
        dotnet --version
        dotnet workload install android ios maccatalyst maui --version ${{ env.NET_VERSION }}

    - name: Set up JDK
      uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00
      with:
        distribution: ${{ env.JAVA_DISTRIBUTION }}
        java-version: ${{ env.JAVA_VERSION }}

    - name: Build
      run: dotnet run --project build/Build.csproj -- --outputDir=${{ env.OUTPUT_DIR }}

    - name: Upload artifacts
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
      with:
        name: build-artifacts
        path: ${{ env.OUTPUT_DIR }}

    - name: NuGet Push
      if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release/')
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_APIKEY }}
        SOURCE_URL: https://api.nuget.org/v3/index.json
      run: |
        dotnet nuget push -s ${{ env.SOURCE_URL }} -k ${{ env.NUGET_AUTH_TOKEN }} ${{ env.OUTPUT_DIR }}/**/*.nupkg

    - name: GitHub Packages Push
      if: github.event_name != 'pull_request'
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GH_PACKAGES_API_KEY }}
        SOURCE_URL: https://nuget.pkg.github.com/cheesebaron/index.json
      run: |
        dotnet nuget push -s ${{ env.SOURCE_URL }} -k ${{ env.NUGET_AUTH_TOKEN }} ${{ env.OUTPUT_DIR }}/**/*.nupkg  
