name: Build

on:
  push:
    branches: 
      - master

  pull_request:
    branches: 
      - master

env:
  JAVA_DISTRIBUTION: 'microsoft'
  JAVA_VERSION: 17
  NET_VERSION: 9.0.102
  OUTPUT_DIR: ${{ github.workspace }}/output

jobs:
  build:
    runs-on: macos-15
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true

    - name: Install .NET ${{ env.NET_VERSION }}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.NET_VERSION }}

    - name: Restore .NET tools
      run: dotnet tool restore

    - name: Install .NET workloads
      run: |
        dotnet --version
        dotnet workload install android ios maccatalyst --version ${{ env.NET_VERSION }}

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: ${{ env.JAVA_DISTRIBUTION }}
        java-version: ${{ env.JAVA_VERSION }}

    - name: Build
      run: dotnet cake --outputDir=${{ env.OUTPUT_DIR }}

    - name: Copy NuGet Packages
      run: |
        mkdir -p ${{ env.OUTPUT_DIR }}
        cp -r ${{ github.workspace }}/source/**/bin/Release/*.nupkg ${{ env.OUTPUT_DIR }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: ${{ env.OUTPUT_DIR }}
